### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by Gitbud1979**

### CODE REVIEW

**Review by Gitbud1979 — COMMENTED** [review]
Looks good. Might change every word that's italic to bold.

**Comment by Gitbud1979** [comment]
One time

**Comment by Stuff4ik** [comment]
.

**Comment by Stuff4ik** [comment]
> .
>

**Comment by Stuff4ik** [comment]
> .m
>

**Comment by Stuff4ik** [comment]
- [ ]

**Pull request merged**
